services:
        # Application & web server
        app:
                container_name: "e-isa"
                build:
                        context: .
                working_dir: /var/www
                volumes:
                        - ./:/var/www
                ports:
                        - 8000:80
                networks:
                        - laravel

networks:
        laravel:
